### ISSUE TITLE
Update Partner Logos.remove logo for UFRJ and add FGV logo

### ISSUE THREAD

**Issue by fccoelho** [thegraphnetwork/thegraphnetwork.github.io#4]
Some Logos are outdated:

#### To remove:

- UFRJ
#### To add

- FGV ![Logo_FGV_EMAp](https://user-images.githubusercontent.com/140123/192831768-125006c9-e1c7-4260-94fb-0dd1690b5978.png)
- Infodengue 
![info_dengue_logo_multicidades_virus](https://user-images.githubusercontent.com/140123/192832181-4262c6f2-aa89-422d-95d1-caf49c6e62f6.png)

- OSL

**Comment by xmnlab** [comment]
I will work on that tomorrow. I was being study mkdocs today 
so I hope to have it ready byt tomorrow.

**Comment by xmnlab** [comment]
Also I am planning a refactor in the frontend side .. as it has a lot of thing that is not necessary and will increase maintenance and maybe will cause troubles in the future

**Comment by xmnlab** [comment]
btw, I am refactoring all the html/css .. because it is using the code from the wp and there is a lot extra code that makes hard the maintenance

**Comment by xmnlab** [comment]
done! thanks!
